name: libnosuta
description: platform libraries for nosuta
version: 0.9.0
publish_to: none

environment:
  sdk: ^3.5.0-323

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: tokyo.oykot.libnosuta
        pluginClass: LibnosutaPlugin
      ios:
        pluginClass: LibnosutaPlugin
      macos:
        pluginClass: LibnosutaPlugin
      web:
